Add a test to see if keys are trusted by the gpg keychain. Also start using git --verify-commit, which doesn't exist in older git versions.
Signed-off-by: Sebastiaan <seb@stiaan.io>

diff --git a/check-commit-signature b/check-commit-signature
--- a/check-commit-signature
+++ b/check-commit-signature
@@ -16,6 +16,9 @@
 # hooks.allowunsignedtags
 #   This boolean sets whether unsigned tags are allowed. By default,
 #   they are not allowed.
+# hooks.allowunverifiedsigs
+#   This boolean sets whether commits/tags signed by 
+#   unverified/untrusted keys are allowed. By default, they are not allowed.
 # hooks.allowcommitsonmaster
 #   This boolean sets whether non-merge commits are allowed on master. By
 #   default, these are not allowed.
@@ -66,6 +69,7 @@ git cat-file -e "$rev_old:.gitconfig" &>/dev/null || exit 0;
 
 allowunsignedcommits=$(git cat-file blob "$rev_old:.gitconfig" | git config --file /dev/stdin --bool hooks.allowunsignedcommits)
 allowunsignedtags=$(git cat-file blob "$rev_old:.gitconfig" | git config --file /dev/stdin --bool hooks.allowunsignedtags)
+allowunverifiedsigs=$(git cat-file blob "$rev_old:.gitconfig" | git config --file /dev/stdin --bool hooks.allowunsignedtags)
 allowcommitsonmaster=$(git cat-file blob "$rev_old:.gitconfig" | git config --file /dev/stdin --bool hooks.allowcommitsonmaster)
 allowhotfixonmaster=$(git cat-file blob "$rev_old:.gitconfig" | git config --file /dev/stdin --bool hooks.allowhotfixonmaster)
 allowdeletebranch=$(git cat-file blob "$rev_old:.gitconfig" | git config --file /dev/stdin --bool hooks.allowdeletebranch)
@@ -91,6 +95,9 @@ git cat-file blob "$rev_old:.gitconfig" | git config --file /dev/stdin --list
 ##   --add '0C83 9FFC C5A6 5925 D91B  F16C FF52 7312 2C52 C4E4'
 ##
 ## Do note that you cannot add a key description if you do it this way.
+##
+## Remember to add the public keys to the server, too, or verification will fail.
+## If allowunverifiedsigs=false, make sure the public keys are signed by a trusted key as well.
 
 readarray -t collaborators < <(git cat-file blob "$rev_old:.gitconfig" | git config --file /dev/stdin --get-all gpgkeys.whitelist)
 
@@ -279,7 +286,12 @@ for commit in $span ; do
 
     ## the following returns non-null if $rev_cur has a signature, and gpg reports
     ## the signature is good:
-    has_good_sig=$(git show --no-patch --format=%H --show-signature "$commit" | grep "^gpg: Good signature")
+    verify_sig=$(git verify-commit --raw "$commit" 2>&1)
+    has_good_sig=$?
+    if [ $has_good_sig -eq 0 ] && [ "$allowunverifiedsigs" != "true" ]; then
+        has_verified_sig=false
+        echo "$verify_sig" | grep -e '^\[GNUPG:\] TRUST_UNDEFINED' >/dev/null || has_verified_sig=true
+    fi
 
     ## the following extracts the signing keyid (either short or long) from the
     ## signature on $rev_cur:
@@ -298,8 +310,14 @@ for commit in $span ; do
             fi
 
             if [ "$allowunsignedcommits" != "true" ]; then
-                if [ -z "$has_good_sig" ]; then
+                if [ "$has_good_sig" -ne 0 ]; then
                     echo "*** Bad signature on commit $commit" >&2
+                    exit 1
+                fi
+
+                if [ "$allowunverifiedsigs" != "true" ] && [ "$has_verified_sig" != "true" ]; then
+                    echo "has_verified_sig $has_verified_sig"
+                    echo "*** Unverified signature on commit $commit" >&2
                     exit 1
                 fi
 
@@ -386,3 +404,4 @@ for commit in $span ; do
     ## increment the current rev to the $commit we just checked:
     rev_cur=$commit
 done
+
